# Generated by Django 5.0.7 on 2025-09-23 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Domains',
                'db_table': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='InterviewEaseApp.domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Interviews',
                'ordering': ['-interview_date'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewEaseApp.interview')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('audio_path', models.FileField(blank=True, null=True, upload_to='answers/audio/')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewEaseApp.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewEaseApp.questions')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
