# Generated by Django 5.0.7 on 2025-09-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewEaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
