# Generated by Django 5.0.7 on 2025-09-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewEaseApp', '0002_alter_domain_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
